# Generated by Django 4.0.4 on 2022-10-20 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_usuario',
            field=models.BooleanField(default=False, max_length=16),
        ),
    ]
