# Generated by Django 4.0.4 on 2022-10-20 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_usuario_id_usuario_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='id_usuario',
            field=models.AutoField(default=1, primary_key=True, serialize=False, unique=True),
        ),
    ]
