# Generated by Django 4.0.4 on 2022-10-20 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_usuario_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
