# Generated by Django 4.0.4 on 2022-10-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0008_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre', models.CharField(max_length=16)),
                ('apellido', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True)),
                ('pwd', models.CharField(max_length=12)),
                ('tipo_usuario', models.BooleanField(default=False, max_length=16)),
            ],
        ),
    ]
