# Generated by Django 4.1.3 on 2022-11-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_ubicacion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='precio',
            field=models.IntegerField(default=0),
        ),
    ]
