# Generated by Django 4.1.3 on 2022-11-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ubicacion_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='lng',
            field=models.FloatField(default=0),
        ),
    ]
