# Generated by Django 4.1.3 on 2022-11-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_ubicacion_lat_alter_ubicacion_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='user',
            field=models.EmailField(max_length=50),
        ),
    ]
