# Generated by Django 4.1.3 on 2022-11-12 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_ubicacion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
