# Generated by Django 4.1.3 on 2022-11-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_ubicacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
