# Generated by Django 4.1.3 on 2022-11-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_ubicacion_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
