# Generated by Django 4.1.3 on 2022-11-12 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_ubicacion_precio_alter_ubicacion_lat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
