# Generated by Django 4.1.3 on 2022-11-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_ubicacion_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ubicacion',
            name='id',
        ),
        migrations.AlterField(
            model_name='ubicacion',
            name='nombre',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
