# Generated by Django 4.0.4 on 2022-11-16 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_remove_ubicacion_id_alter_ubicacion_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArriendoEs',
            fields=[
                ('user', models.EmailField(max_length=50, primary_key=True, serialize=False)),
                ('lat', models.FloatField(default=0)),
                ('lng', models.FloatField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('dueño', models.EmailField(max_length=50)),
            ],
        ),
    ]
