# Generated by Django 4.0.4 on 2022-11-16 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_arriendoes_nombrees_arriendoes_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arriendoes',
            name='fecha',
            field=models.CharField(max_length=50),
        ),
    ]
