# Generated by Django 4.1.3 on 2022-12-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_arriendoes_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ubicacion',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
