# Generated by Django 4.1.3 on 2022-12-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_ubicacion_disponible'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendoes',
            name='h_inicio',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='arriendoes',
            name='h_salida',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
