# Generated by Django 4.1.3 on 2022-12-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_arriendoes_h_inicio_arriendoes_h_salida'),
    ]

    operations = [
        migrations.AddField(
            model_name='arriendoes',
            name='totalPago',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
