# Generated by Django 4.1.3 on 2022-12-12 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_usuario_patente_usuario_rut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('user', models.EmailField(max_length=50)),
                ('nombreEs', models.CharField(default='', max_length=50)),
                ('h_inicio', models.IntegerField(default=0, max_length=50)),
                ('fecha_Pago', models.CharField(max_length=50)),
                ('totalPago', models.CharField(default=0, max_length=50)),
            ],
        ),
    ]
