# Generated by Django 4.1.3 on 2022-12-12 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='h_inicio',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
