# Generated by Django 4.1.3 on 2022-12-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_pago_h_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='id_pago',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
